const $=s=>document.querySelector(s);
const fmt=m=>m<60?m+' min':Math.floor(m/60)+' hr'+(m%60?' '+m%60+' min':'');
const toast=t=>{const e=$('#toast');e.textContent=t;e.className='s';clearTimeout(toast.t);toast.t=setTimeout(()=>e.className='',2000)};
const HOW='Short visual explanations, examples, mini activities, quick knowledge checks and an end-of-session quiz.';
const C={Design:'Type, layout, identity and visual craft.',Technology:'Build useful things with code.',Creative:'Capture, edit and tell stories.',Business:'Practical skills for work.'};
const INT=['Typography','UI/UX','Graphic Design','Branding','Coding','Photography','Illustration','Motion Design','Video Editing','Marketing','Visual Storytelling','Creative Writing'];
const LR=[['school','School student'],['uni','University student'],['pro','Working professional']],LV={school:'Beginner-friendly exploration',uni:'Extracurricular, university level',pro:'Practical, career-oriented'};
const TM=[[30,'30 min'],[60,'1 hr'],[120,'2 hr'],[180,'3+ hrs']],DY=[[2,'1–2 days'],[4,'3–4 days'],[5,'5 days'],[7,'Every day']];
const T={};function tp(id,s,i,t,m,d,desc,con,learn,ex,chk,quiz){T[id]={s,i,t,m,d,desc,con,how:HOW,learn,ex,chk,quiz}}
tp('ty','Design','Typography','Typography Basics',30,'Easy','Learn how type size, weight, spacing and hierarchy work together to create readable and expressive communication.',['Type hierarchy','Font families','Font pairing','Spacing','Readability'],[['Hierarchy','Hierarchy uses size, weight and colour to tell the reader what to read first.'],['Spacing','Line height and letter spacing set the rhythm. Tight text feels dense, open text feels calm.']],'A poster headline at 48pt bold with a 14pt regular subtitle shows hierarchy instantly.',['Which makes a headline stand out most?',['Larger size and heavier weight','Smaller size','Same size as body text'],0,'Size and weight create contrast.'],[['What is type hierarchy?',['Ordering text by importance','Using one font only','Adding colour'],0,'It guides the reader through content.'],['True or false: more line spacing always improves readability.',['True','False'],1,'Too much space breaks lines apart.'],['Two fonts pair best when they...',['Contrast clearly','Look almost identical','Are both decorative'],0,'Clear contrast looks intentional.']]);
tp('ux','Design','UI/UX','UI Layout Basics',45,'Easy','Learn how grids, spacing and alignment organise screens so people know where to look and what to tap.',['Grids and columns','Alignment','Whitespace','Visual flow','Tap targets'],[['Grid','A grid gives every element a place, so screens feel ordered and predictable.'],['Whitespace','Empty space groups related items and gives the eye somewhere to rest.']],'Compare a cramped form with one using even 16px gaps. The second is easier to scan.',['What does whitespace mainly do?',['Groups content and aids focus','Wastes space','Adds decoration'],0,'Space creates grouping and calm.'],[['Why use a layout grid?',['Consistent alignment and rhythm','More colours','Slower pages'],0,'Grids keep screens consistent.'],['True or false: small tap targets improve usability.',['True','False'],1,'Aim for roughly 44px targets.'],['People scan from top left first. This is about...',['Visual flow','Font licensing','File size'],0,'Layouts should follow reading paths.']]);
tp('gd','Design','Graphic Design','Poster Design Principles',60,'Medium','Build posters that read from across a room using contrast, focal points, alignment and restraint.',['Focal point','Contrast','Alignment','Colour','Balance'],[['Focal point','One element should win attention first. Everything else supports it.'],['Contrast','Differences in size, colour and weight make information scannable.']],'A poster with one large image and two lines of text beats one with six competing elements.',['How many main focal points should a poster have?',['One','Five','None'],0,'One dominant element gives clarity.'],[['Contrast helps posters by...',['Making information scannable','Hiding details','Adding decoration'],0,'Contrast separates levels.'],['True or false: more elements make a stronger poster.',['True','False'],1,'Restraint improves clarity.'],['Scenario: nothing stands out. What first?',['Pick a focal point','Add more colours','Shrink the text'],0,'Decide what matters most.']]);
tp('br','Design','Branding','Brand Identity Fundamentals',90,'Medium','Understand how logo, colour, type and voice combine into an identity people recognise and remember.',['Brand purpose','Logo systems','Colour and type','Voice','Consistency'],[['Identity','A brand identity is the set of visual and verbal signals that make a brand recognisable.'],['Consistency','Using the same colours, type and tone everywhere builds trust.']],'Think of a coffee brand: its cup colour, name style and friendly tone all say the same thing.',['What builds recognition most?',['Consistent use of identity','Changing logos often','Using many fonts'],0,'Repetition builds memory.'],[['A brand identity is...',['Visual and verbal signals working together','Only a logo','A price list'],0,'It is a system, not one asset.'],['True or false: a logo alone is a brand.',['True','False'],1,'Brand includes voice, colour, type and experience.'],['Scenario: a cafe uses five styles. The problem?',['Inconsistency','Too little colour','No website'],0,'Mixed signals weaken recognition.']]);
tp('il','Design','Illustration','Illustration: Shape and Line',45,'Easy','Start illustrating by building any subject from simple shapes and confident lines.',['Basic shapes','Line weight','Simplification','Composition'],[['Shapes','Most objects can be built from circles, squares and triangles.'],['Line weight','Thicker lines feel bold and close, thinner lines feel light and distant.']],'Draw a house cat using only circles and triangles, then add line weight.',['Complex objects start as...',['Simple shapes','Fine details','Colour fills'],0,'Shapes first, details later.'],[['Thicker lines usually feel...',['Bolder and closer','Fainter','Random'],0,'Weight changes emphasis.'],['True or false: simplifying removes personality.',['True','False'],1,'Good simplification sharpens style.'],['What should you add last?',['Fine details','The basic shapes','The composition'],0,'Details come after structure.']]);
tp('mo','Design','Motion Design','Motion Design Principles',60,'Medium','Learn timing, easing and choreography so movement explains and delights instead of distracting.',['Timing','Easing','Anticipation','Hierarchy of motion'],[['Easing','Natural motion speeds up and slows down instead of moving at constant speed.'],['Purpose','Good motion shows where something came from or what changed.']],'A menu that eases open in 250ms feels smoother than one that snaps.',['Natural movement usually uses...',['Easing','Constant speed','Random timing'],0,'Objects accelerate and decelerate.'],[['UI motion should mostly...',['Explain change','Show off','Slow users down'],0,'Motion needs purpose.'],['True or false: longer animations are always better.',['True','False'],1,'Long animations feel slow.'],['Which timing suits a small button?',['150 to 250ms','3 seconds','10 seconds'],0,'Quick, subtle feedback.']]);
tp('co','Technology','Coding','Coding Basics: HTML and CSS',45,'Easy','Build your first web page by learning how structure and style work together.',['HTML elements','CSS selectors','Colour and type','Simple layout'],[['HTML','HTML describes what things are: headings, paragraphs, images, links.'],['CSS','CSS describes how things look: colour, size, spacing and layout.']],'Write one heading and one paragraph, then colour the heading purple with CSS.',['What does CSS control?',['How a page looks','What a page is about','Where files are stored'],0,'CSS handles styling.'],[['Which defines a page heading?',['An h1 element','A CSS colour','A JPEG'],0,'h1 is a heading element.'],['True or false: HTML and CSS do the same job.',['True','False'],1,'HTML is structure, CSS is style.'],['To change text colour you use...',['CSS','A new page','An image'],0,'Colour is a style.']]);
tp('ph','Creative','Photography','Photography Composition',30,'Easy','See like a photographer by using framing, light and simple compositional rules.',['Rule of thirds','Leading lines','Light','Framing'],[['Thirds','Place subjects along third lines rather than dead centre for a dynamic image.'],['Leading lines','Roads, rails and edges guide the eye toward the subject.']],'Photograph one object three ways: centred, on a third, and framed by a doorway.',['Rule of thirds suggests placing the subject...',['Off centre on a third line','Always centre','At the very edge'],0,'Off-centre often feels more dynamic.'],[['Leading lines do what?',['Guide the eye','Hide the subject','Add noise'],0,'They direct attention.'],['True or false: the subject must always be centred.',['True','False'],1,'Centre works sometimes, not always.'],['Soft light is usually found...',['Near sunrise or sunset','At noon','Under bright bulbs only'],0,'Low sun is softer.']]);
tp('ve','Creative','Video Editing','Video Editing Essentials',60,'Medium','Cut footage into a clear story using pacing, transitions, sound and a simple timeline workflow.',['Timeline basics','Cuts and pacing','Transitions','Audio'],[['Cut','Cut on action so movement carries the viewer across shots.'],['Audio','Viewers forgive soft video but not bad audio.']],'Trim a 30 second clip to 10 seconds and feel how pacing changes.',['Good editors often cut...',['On action','Randomly','Only at the end'],0,'Action hides the cut.'],[['What matters most to viewers?',['Clear audio','A fancy transition','Long intros'],0,'Audio problems stand out.'],['True or false: more transitions make a better edit.',['True','False'],1,'Simple cuts usually work best.'],['Pacing means...',['The rhythm of cuts','The file size','The screen ratio'],0,'Pacing is rhythm.']]);
tp('vs','Creative','Visual Storytelling','Visual Storytelling',45,'Easy','Learn how sequence, framing and detail can tell a story without many words.',['Story arc','Sequence','Framing','Detail'],[['Arc','A story sets up a situation, raises tension and then resolves it.'],['Sequence','Order changes meaning. The same images can tell different stories.']],'Order three photos: a door, a face, a letter. Change the order and change the story.',['Changing the order of images can...',['Change the story','Change nothing','Delete the story'],0,'Sequence shapes meaning.'],[['A story arc usually includes...',['Setup, tension, resolution','Only a beginning','Only a logo'],0,'Arcs move through stages.'],['True or false: detail shots can carry emotion.',['True','False'],0,'A single object can suggest a lot.'],['Framing decides...',['What the viewer notices','Paper colour','Font size only'],0,'Frame equals focus.']]);
tp('cw','Creative','Creative Writing','Creative Writing: Finding Your Voice',30,'Easy','Discover your writing voice through specific detail, rhythm and honest observation.',['Voice','Specific detail','Rhythm','Show vs tell'],[['Specific detail','One exact detail beats three vague ones.'],['Show not tell','Show the rain on the window instead of saying it was sad.']],'Rewrite She was nervous using only what her hands and eyes do.',['Which is more specific?',['Her hands trembled on the cup','She felt bad','It was a feeling'],0,'Concrete detail wins.'],[['Voice is...',['The personality in your writing','Font choice','Word count'],0,'Voice is how you sound.'],['True or false: vague words make writing stronger.',['True','False'],1,'Specific words land harder.'],['Show not tell means...',['Use action and detail','Explain everything','Avoid verbs'],0,'Let details carry feeling.']]);
tp('mk','Business','Marketing','Marketing Basics',45,'Easy','Understand audiences, messages and channels so you can share an idea or project with the right people.',['Audience','Message','Channels','Measuring results'],[['Audience','Start with who you want to reach and what they care about.'],['Message','A clear message says what you offer and why it matters in one line.']],'Write one sentence for your own project: who it helps and how.',['Marketing starts with...',['Knowing your audience','Choosing a colour','Buying ads'],0,'Audience first.'],[['A good message is...',['Clear and specific','Long and vague','Full of jargon'],0,'Clarity wins.'],['True or false: every channel suits every audience.',['True','False'],1,'Go where your audience is.'],['Why measure results?',['To learn what works','To look busy','To avoid planning'],0,'Data guides decisions.']]);
Object.values(T).forEach((t,k)=>{const r=(q,j)=>{const n=q[1].length,s=(k+j)%n;q[1]=q[1].slice(s).concat(q[1].slice(0,s));q[2]=(q[2]-s+n)%n};r(t.chk,0);t.quiz.forEach((q,j)=>r(q,j+1))});
const st={learner:'',interests:[],daily:0,days:0,avail:60,bag:[],later:[],plan:null,done:{},mins:0,streak:0,last:'',week:[0,0,0,0,0,0,0],seen:[],recent:[],ob:false,page:'home',cur:'',ang:0,S:null,cat:'All'};
const KEYS=['learner','interests','daily','days','avail','bag','later','done','mins','streak','last','week','seen','recent','ob'];
function save(){try{localStorage.setItem('be2',JSON.stringify(Object.fromEntries(KEYS.map(k=>[k,st[k]]))))}catch(e){}}
try{Object.assign(st,JSON.parse(localStorage.getItem('be2')||'{}'))}catch(e){}
const load=()=>st.bag.reduce((a,b)=>a+b.today,0);
function seenAdd(id){const i=T[id].i;if(!st.seen.includes(i))st.seen.push(i)}
function streak(id){const d=new Date(),k=d.toDateString(),y=new Date(Date.now()-864e5).toDateString();if(st.last!==k){st.streak=st.last===y?st.streak+1:1;st.last=k}st.week[(d.getDay()+6)%7]+=T[id].m;seenAdd(id);save()}
function nav(){const n=st.bag.length,p=st.page,l=(k,t,g)=>`<button class="b ${p===k?'on':''}" onclick="go('${g||k}')">${t}</button>`;
$('#nav').innerHTML=`<div class="logo" onclick="go('home')"><svg width="30" height="30" viewBox="0 0 30 30" fill="none" stroke="#6B43D6" stroke-width="2"><path d="M15 5v18M8 24h14M5 11l10-3 10 3"/><path d="M2 17l3-6 3 6a3.5 3.5 0 01-6 0zM22 17l3-6 3 6a3.5 3.5 0 01-6 0z" stroke="#405CFF"/></svg>BALANCE-ED</div>${l('explore','Explore',st.ob?'explore':'home')}${l('bag','My Learning Bag'+(n?' ('+n+')':''))}${l('progress','Progress')}${l('signup','Sign up')}${l('login','Log in')}`}
function go(pg,a,keep){st.page=pg;if(a)st.cur=a;nav();const f={home,ob1,ob2,ob3,explore,detail,bag,plan,session,progress,login:()=>auth('login'),signup:()=>auth('signup')}[pg];$('#app').innerHTML=`<div class="pg">${f()}</div>`;if(!keep)scrollTo(0,0);if(pg==='bag')setScale();save()}
function add(id){if(st.bag.some(b=>b.id===id))return toast('Already in your bag');st.bag.push({id,today:T[id].m,tom:0});st.later=st.later.filter(x=>x!==id);seenAdd(id);toast('Added to your Learning Bag');go(st.page,0,1)}
function rem(id){st.bag=st.bag.filter(b=>b.id!==id);go('bag',0,1)}
function later(id){st.bag=st.bag.filter(b=>b.id!==id);if(!st.later.includes(id))st.later.push(id);toast(T[id].t+' saved for later');go('bag',0,1)}
const FL=(x,y,d,c)=>`<g transform="translate(${x} ${y})"><g class="fl" style="animation-delay:${d}s">${c}</g></g>`;
function home(){const hw=[['DISCOVER','Find something you are interested in.'],['PICK','Choose topics you want to learn.'],['WEIGH','Compare your learning load with the time you have.'],['BALANCE','Remove, split or move topics when your bag gets too heavy.'],['LEARN','Start a realistic learning session.']];
return`<section class="wrap hero"><div><div class="eye">A Learning Capacity Tool</div><h1>What do you want<br>to learn today?</h1><p class="sub">BALANCE-ED helps you discover extracurricular subjects, build useful skills, and make room for learning alongside everything else you already do.</p><p class="sub">Choose what interests you, decide how much time you can realistically give, and let your Learning Bag help you balance what you want to learn with the time you actually have.</p><div class="row"><button class="b d" onclick="go('${st.ob?'explore':'ob1'}')">${st.ob?'Go to Explore':'Get started'}</button><button class="b" onclick="document.getElementById('how').scrollIntoView({behavior:'smooth'})">How it works</button></div></div>
<svg viewBox="0 0 420 340" style="width:100%;max-width:460px;justify-self:center" fill="none" role="img" aria-label="Topic cards dropping into a learning bag"><rect x="10" y="10" width="400" height="320" rx="44" fill="#F0EAFF"/><g class="sw"><path d="M130 205h160l16 100a12 12 0 01-12 12H126a12 12 0 01-12-12z" fill="#fff" stroke="#6B43D6" stroke-width="2.5"/><path d="M170 205v-16a40 40 0 0180 0v16" stroke="#6B43D6" stroke-width="2.5"/><rect x="150" y="250" width="120" height="6" rx="3" fill="#E2D8F5"/></g><g transform="translate(155 40) rotate(-6 55 26)"><g class="cd" style="animation-delay:0s"><rect width="110" height="52" rx="12" fill="#fff" stroke="#E2D8F5"/><rect x="14" y="14" width="34" height="6" rx="3" fill="#6B43D6"/><text x="14" y="38" font-family="DM Mono" font-size="12" fill="#171717">Typography</text></g></g><g transform="translate(160 40) rotate(4 55 26)"><g class="cd" style="animation-delay:3s"><rect width="110" height="52" rx="12" fill="#fff" stroke="#E2D8F5"/><rect x="14" y="14" width="34" height="6" rx="3" fill="#405CFF"/><text x="14" y="38" font-family="DM Mono" font-size="12" fill="#171717">Coding</text></g></g><g transform="translate(150 40) rotate(-2 55 26)"><g class="cd" style="animation-delay:6s"><rect width="110" height="52" rx="12" fill="#fff" stroke="#E2D8F5"/><rect x="14" y="14" width="34" height="6" rx="3" fill="#6B43D6"/><text x="14" y="38" font-family="DM Mono" font-size="12" fill="#171717">Photography</text></g></g><text x="210" y="312" text-anchor="middle" font-family="DM Mono" font-size="11" fill="#777" style="letter-spacing:.12em">PICK → BAG → WEIGH</text></svg></section>
<section class="lav"><div class="wrap"><div class="eye">Extracurricular learning</div><h2>Learn beyond your curriculum.</h2><p class="sub">Explore skills and subjects that sit outside your regular curriculum, from design and technology to creative and practical skills.</p></div></section>
<section class="wrap" id="how"><div class="eye">How BALANCE-ED works</div><div class="hw">${hw.map((x,i)=>`<div><b>0${i+1}</b><span class="mono">${x[0]}</span><p style="margin:6px 0 0">${x[1]}</p></div>`).join('')}</div><button class="b d" onclick="go('${st.ob?'explore':'ob1'}')">${st.ob?'Go to Explore':'Get started'}</button></section>`}
function obw(n,body){return`<section class="wrap" style="max-width:760px"><div class="steps">${['About you','Interests','Goal'].map((x,i)=>`<span class="${i+1===n?'a':''}">0${i+1} ${x}</span>`).join('')}</div>${body}</section>`}
const H1='<h1 style="font-size:clamp(34px,6vw,58px)">',Q='<p style="font-weight:500;margin-top:26px">';
function ob1(){return obw(1,`${H1}Before we begin...</h1><p class="sub">Tell us a little about how you learn.</p>${Q}Who are you learning alongside?</p><div class="row">${LR.map(x=>`<button class="b ${st.learner===x[0]?'on':''}" onclick="st.learner='${x[0]}';go('ob1',0,1)">${x[1]}</button>`).join('')}</div><div class="row" style="margin-top:28px"><button class="b" onclick="go('home')">Back</button><button class="b d" ${st.learner?'':'disabled'} onclick="go('ob2')">Continue</button></div>`)}
function tg(i){const a=st.interests,k=a.indexOf(INT[i]);k<0?a.push(INT[i]):a.splice(k,1);go('ob2',0,1)}
function ob2(){return obw(2,`${H1}What would you like to explore?</h1><p class="sub">Choose a few things you are curious about.</p><div class="row" style="margin-top:24px">${INT.map((x,i)=>`<button class="b ${st.interests.includes(x)?'on':''}" onclick="tg(${i})">${x}</button>`).join('')}</div><div class="row" style="margin-top:28px"><button class="b" onclick="go('ob1')">Back</button><button class="b d" ${st.interests.length?'':'disabled'} onclick="go('ob3')">Continue</button></div>`)}
function ob3(){const w=st.daily*st.days/60;return obw(3,`${H1}How much time can you realistically give learning?</h1><p class="sub">Your learning plan works around your schedule, not the other way around.</p>${Q}How much time would you like to learn each day?</p><div class="row">${TM.map(x=>`<button class="b ${st.daily===x[0]?'on':''}" onclick="st.daily=${x[0]};go('ob3',0,1)">${x[1]}</button>`).join('')}</div>${Q}How many days a week?</p><div class="row">${DY.map(x=>`<button class="b ${st.days===x[0]?'on':''}" onclick="st.days=${x[0]};go('ob3',0,1)">${x[1]}</button>`).join('')}</div>${w?`<div class="card" style="margin-top:24px"><div class="mono">YOUR PLANNED CAPACITY</div><div class="big">${+w.toFixed(1)} hours / week</div></div>`:''}<div class="row" style="margin-top:28px"><button class="b" onclick="go('ob2')">Back</button><button class="b d" ${w?'':'disabled'} onclick="st.ob=true;st.avail=st.daily;go('explore')">See my recommendations</button></div>`)}
function rec(){const L=st.learner,sc=t=>(st.interests.includes(t.i)?10:0)+(L==='school'&&t.d==='Easy'?3:0)+(L==='pro'&&['Business','Technology'].includes(t.s)?3:0)+(L==='uni'&&t.d==='Medium'?1:0)-(t.m>st.daily?1:0);return Object.keys(T).sort((a,b)=>sc(T[b])-sc(T[a])).slice(0,6)}
function tc(id){const t=T[id],b=st.bag.some(x=>x.id===id);return`<div class="card"><span class="mono">${t.s.toUpperCase()} · ${t.i.toUpperCase()}</span><div><span class="tag">${t.d}</span></div><h3>${t.t}</h3><p class="sub" style="margin:0">${t.desc}</p><span class="mono">${fmt(t.m)}</span><div class="row"><button class="b" onclick="go('detail','${id}')">View details</button><button class="b d" ${b?'disabled':''} onclick="add('${id}')">${b?'In bag':'Add to bag'}</button></div></div>`}
function explore(){const cats=['All',...Object.keys(C)],list=Object.keys(T).filter(i=>st.cat==='All'||T[i].s===st.cat);
return`<section class="wrap"><div class="eye">${LV[st.learner]||'Explore'}${st.daily?' · '+fmt(st.daily)+' a day':''}</div><h2>Picked for you</h2><p class="sub">Based on your interests and available learning time.</p><div class="grid3">${rec().map(tc).join('')}</div></section>
<section class="lav"><div class="wrap"><div class="eye">Browse</div><h2>Learn beyond your curriculum</h2><div class="row">${cats.map((c,i)=>`<button class="b ${st.cat===c?'on':''}" onclick="st.cat='${c}';go('explore',0,1)">${c}</button>`).join('')}</div><p class="sub" style="margin-top:12px">${C[st.cat]||'Design, technology, creative and practical skills.'}</p><div class="grid3">${list.map(tc).join('')}</div></div></section>
${st.later.length?`<section class="wrap"><div class="eye">Saved</div><h2>Saved for later</h2><div class="grid3">${st.later.map(tc).join('')}</div></section>`:''}`}
function detail(){const id=st.cur,t=T[id];seenAdd(id);st.recent=[id,...st.recent.filter(x=>x!==id)].slice(0,4);const b=st.bag.some(x=>x.id===id);
return`<section class="wrap"><button class="b" onclick="go('explore')">Back to topics</button><div class="eye" style="margin-top:32px">${t.s} · ${t.i}</div>${H1}${t.t}</h1><div class="row"><span class="tag">${t.d}</span><span class="tag">Estimated time: ${fmt(t.m)}</span></div><p class="sub" style="margin-top:16px">${t.desc}</p><div class="two" style="margin-top:24px"><div class="card"><h3>What you'll learn</h3><ul>${t.con.map(c=>`<li>${c}</li>`).join('')}</ul></div><div class="card"><h3>How you'll learn</h3><p>${t.how}</p><p class="mono" style="margin:0">Estimated time: ${fmt(t.m)} · Quiz: ${t.quiz.length} questions</p></div></div><div class="row" style="margin-top:24px"><button class="b d" ${b?'disabled':''} onclick="add('${id}')">${b?'In your bag':'Add to Learning Bag'}</button><button class="b" onclick="start('${id}')">Start learning</button></div></section>`}
function bag(){const L=load(),A=st.avail,over=L>A,n=st.bag.length,tom=st.bag.reduce((a,b)=>a+b.tom,0),big=st.bag.slice().sort((a,b)=>b.today-a.today)[0];
const cards=n?st.bag.map(b=>{const t=T[b.id];return`<div class="card" style="${over&&b.id===big.id?'border-color:var(--p);box-shadow:0 0 0 3px #F0EAFF':''}"><span class="mono">${t.s.toUpperCase()}</span><h3 style="font-size:20px">${t.t}</h3><div class="row" style="padding:0"><span class="tag">${fmt(b.today)}${b.tom?' today':''}</span><span class="tag">${t.d}</span>${b.tom?`<span class="tag">+${fmt(b.tom)} tomorrow</span>`:''}</div><div class="row"><button class="b" onclick="go('detail','${b.id}')">View details</button><button class="b" onclick="later('${b.id}')">Save for later</button><button class="b d" onclick="rem('${b.id}')">Remove</button></div></div>`}).join(''):`<div class="card"><p>Your bag is empty.</p><button class="b" onclick="go('explore')">Explore topics</button></div>`;
let msg='';if(n)msg=over?`<h2>Your bag is a little heavy.</h2><p class="sub">You have chosen more learning than you have time for today.</p><div class="row"><button class="b" onclick="toast('Use Remove on any topic above');scrollTo(0,0)">Remove a topic</button><button class="b" onclick="document.getElementById('split').scrollIntoView({behavior:'smooth'})">Split a topic</button><button class="b" onclick="later('${big.id}')">Save for later</button></div>`:`<h2>Your learning is balanced.</h2><p class="sub">You have enough time for everything you have chosen today.</p><div class="mono">Remaining: ${fmt(A-L)}</div><div class="row" style="margin-top:12px"><button class="b d" onclick="startPlan()">Start learning</button></div>`;
const rm=big?Math.max(0,A-(L-big.today)):0,pool=over&&big?Object.keys(T).filter(id=>!st.bag.some(x=>x.id===id)&&T[id].m<=rm):[],same=pool.filter(id=>T[id].s===T[big.id].s),sim=(same.length?same:pool).sort((x,y)=>((T[y].i===T[big.id].i)-(T[x].i===T[big.id].i))||T[y].m-T[x].m).slice(0,3);
const sg=over&&big?`<div class="wrap" style="padding-top:0"><div class="eye">Want something lighter?</div><h2 style="font-size:clamp(26px,4vw,38px)">Similar topics that fit</h2><p class="sub">Instead of ${T[big.id].t}, you have ${fmt(rm)} left today. Switch to a ${same.length?T[big.id].s.toLowerCase()+' topic':'topic'} that fits.</p>${sim.length?`<div class="grid3">${sim.map(id=>{const t=T[id];return`<div class="card"><span class="mono">${t.s.toUpperCase()} · ${t.i.toUpperCase()}</span><h3 style="font-size:20px">${t.t}</h3><div class="row" style="padding:0"><span class="tag">${fmt(t.m)}</span><span class="tag">${t.d}</span><span class="tag">fits, ${fmt(rm-t.m)} spare</span></div><div class="row"><button class="b" onclick="go('detail','${id}')">View details</button><button class="b d" onclick="swap('${big.id}','${id}')">Switch topic</button></div></div>`}).join('')}</div>`:'<div class="card"><p style="margin:0">Nothing similar fits the remaining time. Try splitting it or saving it for later.</p></div>'}</div>`:'';
const sp=over&&big?`<div class="wrap" id="split" style="padding-top:0"><div class="card"><div class="eye">Split a topic</div><h3>This topic is too much for today.</h3><p class="mono">${T[big.id].t} · ${fmt(big.today+big.tom)} · Available today ${fmt(Math.max(5,rm))}</p><input type="range" id="sl" min="5" max="${big.today+big.tom}" step="5" value="${Math.min(big.today,Math.max(5,rm))}" oninput="slv()"><div class="row" style="gap:32px"><div>Today <b id="st">–</b></div><div>Tomorrow <b id="sm">–</b></div></div><div class="row"><button class="b d" onclick="split('${big.id}')">Split &amp; balance</button></div></div></div>`:'';
const tm=!over&&tom?`<div class="wrap" style="padding-top:0"><div class="card"><div class="eye">Balanced</div><p class="mono" style="margin:0">Today ${fmt(L)} · Tomorrow ${fmt(tom)}</p><button class="b" onclick="st.bag.forEach(b=>{b.today+=b.tom;b.tom=0});go('bag')">Move tomorrow's part to today</button></div></div>`:'';
return`<section class="wrap"><h1 style="font-size:clamp(36px,6vw,64px)">Your Learning Bag</h1><p class="sub">Everything you have picked, with its true time cost.</p><div class="two bg"><div class="bl">${cards}</div><div class="card stick" style="text-align:center">${scaleSVG()}<div style="text-align:left">${n?`<div class="row" style="gap:32px"><div><div class="mono">LEARNING LOAD</div><div class="big">${fmt(L)}</div></div><div><div class="mono">TODAY'S CAPACITY</div><div class="big">${fmt(A)}</div></div></div>`:''}${msg}<div class="row" style="margin-top:14px">${TM.map(x=>`<button class="b ${A===x[0]?'on':''}" onclick="setAvail2(${x[0]})">${x[1]}</button>`).join('')}</div></div></div></div></section>
${sg||sp||tm?`<section class="lav"><div class="wrap" style="padding:0"></div><div style="padding:48px 0 8px">${sg}${sp}${tm}</div></section>`:''}`}
function swap(o,n){const i=st.bag.findIndex(b=>b.id===o);if(i<0)return;st.bag[i]={id:n,today:T[n].m,tom:0};seenAdd(n);toast('Switched to '+T[n].t);go('bag',0,1)}
function progress(){const ids=Object.keys(st.done),wk=st.week,mx=Math.max(...wk,30),tot=wk.reduce((a,b)=>a+b,0),cap=st.daily*st.days,h=Math.floor(st.mins/60),li=(a,f)=>a.length?a.map(f).join(''):'<p class="mono">Nothing here yet.</p>';
return`<section class="wrap"><h1 style="font-size:clamp(36px,6vw,64px)">Your Progress</h1><p class="sub">A calm look at what you have learned. No rankings, just reflection.</p><div class="stats"><div class="card"><div class="mono">SUBJECTS EXPLORED</div><div class="big">${st.seen.length}</div></div><div class="card"><div class="mono">TOPICS COMPLETED</div><div class="big">${ids.length}</div></div><div class="card"><div class="mono">LEARNING TIME</div><div class="big">${h?h+'h ':''}${st.mins%60}m</div></div><div class="card"><div class="mono">CURRENT STREAK</div><div class="big">${st.streak} day${st.streak===1?'':'s'}</div></div></div>
<div class="two"><div class="card"><h3>Learning this week</h3><div class="wk">${wk.map((v,i)=>`<div><i style="height:${Math.round(v/mx*80)}px"></i>${'MTWTFSS'[i]}</div>`).join('')}</div>${cap?`<div class="bar"><i style="width:${Math.min(100,tot/cap*100)}%"></i></div><p class="mono" style="margin:0">${fmt(tot)} of ${fmt(cap)} planned</p>`:''}</div>
<div class="card"><h3>Recently explored</h3>${li(st.recent,id=>`<div class="row" style="padding:2px 0"><span style="flex:1">${T[id].t}</span><button class="b" onclick="go('detail','${id}')">View details</button></div>`)}<h3 style="margin-top:14px">Completed topics</h3>${li(ids,id=>`<div class="row" style="padding:2px 0"><span style="flex:1">${T[id].t}</span><span class="mono">${st.done[id]} / ${T[id].quiz.length} correct</span></div>`)}</div></div><div class="row" style="margin-top:24px"><button class="b" onclick="go('explore')">Explore topics</button></div></section>`}
function scaleSVG(){return`<svg viewBox="0 0 400 250" style="width:100%;max-width:460px"><path d="M200 70v150M150 224h100" stroke="#6B43D6" stroke-width="5" stroke-linecap="round"/><g id="beam" style="transition:transform .9s cubic-bezier(.3,1.4,.5,1);transform-origin:200px 70px"><path d="M60 70h280" stroke="#171717" stroke-width="4" stroke-linecap="round"/><g id="pl" style="transition:transform .9s cubic-bezier(.3,1.4,.5,1);transform-origin:60px 70px"><path d="M60 70l-38 60h76zM22 130h76a38 22 0 01-76 0z" fill="#F0EAFF" stroke="#6B43D6" stroke-width="2"/><text x="60" y="122" text-anchor="middle" font-size="11" font-family="DM Mono" fill="#6B43D6">LOAD</text></g><g id="pr" style="transition:transform .9s cubic-bezier(.3,1.4,.5,1);transform-origin:340px 70px"><path d="M340 70l-38 60h76zM302 130h76a38 22 0 01-76 0z" fill="#fff" stroke="#405CFF" stroke-width="2"/><text x="340" y="122" text-anchor="middle" font-size="11" font-family="DM Mono" fill="#405CFF">TIME</text></g></g><circle cx="200" cy="70" r="9" fill="#6B43D6"/></svg>`}
function setScale(){const L=load(),A=st.avail,a=L?Math.max(-18,Math.min(18,-(L-A)/Math.max(L,A)*30)):0;const nb=a=>{const b=$('#beam');if(!b)return;b.style.transform=`rotate(${a}deg)`;$('#pl').style.transform=`rotate(${-a}deg)`;$('#pr').style.transform=`rotate(${-a}deg)`};nb(st.ang);requestAnimationFrame(()=>requestAnimationFrame(()=>{nb(a);st.ang=a}))}
function setAvail2(m){st.avail=m;go('bag')}
function slv(tot){const s=$('#sl');if(!s)return;tot=+s.max;$('#st').textContent=fmt(+s.value);$('#sm').textContent=fmt(tot-s.value)}
function split(id){const b=st.bag.find(x=>x.id===id),v=+$('#sl').value,tot=b.today+b.tom;b.today=v;b.tom=tot-v;toast(load()<=st.avail?'Balanced':'Split saved. Keep adjusting');go('bag')}
setTimeout(()=>{},0);
const _go=go;go=function(p,a,k){_go(p,a,k);if(p==='bag')setTimeout(()=>slv(),30)};
function startPlan(){st.plan=st.bag.map(b=>({...b}));go('plan')}
function plan(){const p=st.plan||[],tot=p.reduce((a,b)=>a+b.today,0);
return`<section class="wrap"><div class="eye">Balanced</div><h1 style="font-size:clamp(36px,6vw,64px)">Today's Learning</h1><div class="list">${p.map((b,i)=>{const t=T[b.id];return`<div class="mod"><div class="n">${i+1}</div><div><h3 style="margin:0;font-size:20px">${t.s} — ${t.t}</h3><span class="mono">${fmt(b.today)}${st.done[b.id]!=null?' · complete':''}</span></div><div class="row"><button class="b d" onclick="start('${b.id}')">${st.done[b.id]!=null?'Review':'Start learning'}</button></div></div>`}).join('')}</div>
<div class="card" style="margin-top:24px"><div class="mono">TOTAL</div><div class="big">${fmt(tot)}</div><p class="sub" style="margin:0">${st.avail>=tot?fmt(st.avail-tot)+' remaining':'Over by '+fmt(tot-st.avail)}</p></div></section>`}
function start(id){st.S={id,step:0,qi:0,score:0,tried:false,fb:null};go('session')}
function pct(){const S=st.S,n=T[S.id].quiz.length;return S.step===0?10:S.step===1?25:S.step===2?40:S.step===3?40+Math.round(S.qi/n*55):100}
function session(){const S=st.S,t=T[S.id],q=t.quiz,labels=['Learn','Interact','Check','Quiz','Complete'];
const head=`<button class="b" onclick="go('${st.plan&&st.plan.some(x=>x.id===S.id)?'plan':'explore'}')">Back to topics</button><div class="eye" style="margin-top:28px">${t.s} · ${t.i}</div><h1 style="font-size:clamp(34px,6vw,60px)">${t.t}</h1><p class="mono">${t.m} min · ${t.d} · ${pct()}% complete</p><div class="bar"><i style="width:${pct()}%"></i></div><div class="steps">${labels.map((l,i)=>`<span class="${i===S.step?'a':''}">${l}</span>`).join('')}</div>`;
let body='';
if(S.step===0)body=t.learn.map(l=>`<div class="def"><b>${l[0]}</b><br>${l[1]}</div>`).join('')+`<button class="b d" onclick="nx()">Continue</button>`;
else if(S.step===1)body=`<div class="card"><div class="eye">Example</div><p style="font-size:19px">${t.ex}</p></div><div class="row" style="margin-top:16px"><button class="b" onclick="S0(-1)">Back to topics</button><button class="b d" onclick="nx()">Continue</button></div>`.replace("S0(-1)","st.S.step=0;go('session')");
else if(S.step===2){const c=t.chk;body=`<div class="card"><div class="eye">Quick check</div><h3 style="font-size:22px">${c[0]}</h3>${c[1].map((o,i)=>`<button class="b opt ${S.fb!=null&&i===c[2]?'ok':''}" onclick="ans(${i})">${o}</button>`).join('')}${S.fb!=null?`<div class="fb"><b>${S.fb===c[2]?'Correct.':'Not quite.'}</b> ${c[3]}</div>`:''}</div>${S.fb===c[2]?'<div class="row" style="margin-top:16px"><button class="b d" onclick="nx()">Take quiz</button></div>':''}`}
else if(S.step===3){const c=q[S.qi];body=`<div class="card"><div class="eye">Question ${S.qi+1} of ${q.length}</div><h3 style="font-size:22px">${c[0]}</h3>${c[1].map((o,i)=>`<button class="b opt ${S.fb!=null?(i===c[2]?'ok':i===S.fb?'no':''):''}" onclick="ans(${i})">${'ABCD'[i]}. ${o}</button>`).join('')}${S.fb!=null?`<div class="fb"><b>${S.fb===c[2]?'Correct.':'Not quite.'}</b> ${c[3]}</div>`:''}</div>${S.fb===c[2]?`<div class="row" style="margin-top:16px"><button class="b d" onclick="nq()">${S.qi+1<q.length?'Continue':'Submit answers'}</button></div>`:''}`}
else body=`<div class="card" style="text-align:center;padding:48px 24px"><div class="big">${S.score} / ${q.length} correct</div><h2 style="margin-top:12px">Topic complete</h2><p class="sub" style="margin:0 auto 16px">Your progress has been saved.</p><div class="row" style="justify-content:center"><button class="b d" onclick="go('${st.plan&&st.plan.length?'plan':'progress'}')">Continue learning</button><button class="b" onclick="go('progress')">Progress</button></div></div>`;
return`<section class="wrap" style="max-width:760px">${head}${body}</section>`}
function nx(){st.S.step++;st.S.fb=null;go('session')}
function ans(i){const S=st.S;if(S.fb!=null&&S.fb===(S.step===2?T[S.id].chk[2]:T[S.id].quiz[S.qi][2]))return;S.fb=i;if(S.step===3&&!S.tried){S.tried=true;if(i===T[S.id].quiz[S.qi][2])S.score++}go('session')}
function nq(){const S=st.S;S.qi++;S.fb=null;S.tried=false;if(S.qi>=T[S.id].quiz.length){S.step=4;if(st.done[S.id]==null)st.mins+=T[S.id].m;st.done[S.id]=Math.max(st.done[S.id]||0,S.score);streak(S.id)}go('session')}
function auth(k){const su=k==='signup';
return`<section class="wrap"><div class="auth card" style="padding:36px"><div class="logo" style="margin:0 0 16px">BALANCE-ED</div><h2 style="font-size:34px">${su?'Create an account':'Welcome back'}</h2><label>Username<input type="text" id="u" autocomplete="off"></label><label>Password<input type="password" id="pw"></label>${su?'<label>Confirm password<input type="password" id="pw2"></label>':'<p><button class="b" style="border-color:transparent;padding-left:0" onclick="toast(\'Prototype: no reset needed\')">Forgot password?</button></p>'}<div class="row"><button class="b d" onclick="doAuth(${su})">${su?'Sign up':'Log in'}</button><button class="b" onclick="go('${su?'login':'signup'}')">${su?'Log in':'Sign up'}</button></div></div></section>`}
function doAuth(su){const u=$('#u').value.trim();if(!u)return toast('Enter a username');if(su&&$('#pw').value!==$('#pw2').value)return toast('Passwords do not match');toast(su?'Account created (prototype)':'Welcome back, '+u);go('home')}
go('home');
